#!/bin/bash

#
# Copyright (C) 2024 Christoph Sommer <sommer@cms-labs.org>
#
# Documentation for this app is at https://github.com/sommer/window-mirror
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

#
# Wrapper script.
# Runs `poetry` with the project directory as its current directory, but not the script.
#

START_DIR="$(pwd)"
SCRIPT=$(realpath "$0").py
PROJECT_DIR="$(dirname $SCRIPT)"

cd "$PROJECT_DIR"
exec poetry run -- bash -c '
start="$1"; shift
proj="$1"; shift
cd "$start"
exec python "${proj}" "$@"
' -- "$START_DIR" "$SCRIPT" "$@"
